In [1]:
###Section A: Data Structures & Control Structures

In [3]:
#1.Create a list of 5 integers. Perform and print the result of the following operations:append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [28]:
list1=[1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [29]:
# append
list1.append(6)
list1

[1, 2, 3, 4, 5, 6]

In [30]:
#extend
list1.extend([7,8])
list1

[1, 2, 3, 4, 5, 6, 7, 8]

In [31]:
# insert
list1.insert(3,2)
list1

[1, 2, 3, 2, 4, 5, 6, 7, 8]

In [32]:
# remove
list1.remove(3)
list1

[1, 2, 2, 4, 5, 6, 7, 8]

In [34]:
# pop
list1.pop(7)
list1

[1, 2, 2, 4, 5, 6, 7]

In [35]:
# clear
list1.clear()
list1

[]

In [50]:
# index
list2=[1,4,6,5,10]
list2.index(4)

1

In [51]:
#count
list2.count(6)

1

In [52]:
list2.sort()
list2

[1, 4, 5, 6, 10]

In [54]:
# reverse
list2.reverse()
list2

[10, 6, 5, 4, 1]

In [55]:
### 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [56]:
# Create a tuple
t1=('koushik','sai','mani')

In [ ]:
# trying to change second name in tuple
try:
  t1[1] = 'chenna'
except TypeError as e:
  print(e)

In [71]:
'''Since tuple is immutable.we can't assign a new value to a tuple which is already presented.'''

"Since tuple is immutable.we can't assign a new value to a tuple which is already presented."

In [72]:
#3.Create a set of integers with some duplicate values. Print the set and explain the output.

In [73]:
set={1,2,2,3,3,4,4,5,6,6,9,9,7,7}
print(set)

{1, 2, 3, 4, 5, 6, 7, 9}


In [75]:
'''explaining: in set duplicates are removed and only unique elements will be presented in set'''

'explaining: in set duplicates are removed and only unique elements will be presented in set'

In [76]:
#4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [77]:
dict1={'Names':['koushik','sai','mani'],'age':[22,21,24],'city':['ap','hyderabad','bangalore']}

In [78]:
dict1

{'Names': ['koushik', 'sai', 'mani'],
 'age': [22, 21, 24],
 'city': ['ap', 'hyderabad', 'bangalore']}

In [79]:
# uptading the age
dict1['age']=[23,24,25]
dict1

{'Names': ['koushik', 'sai', 'mani'],
 'age': [23, 24, 25],
 'city': ['ap', 'hyderabad', 'bangalore']}

In [80]:
# Adding a new key 'email'
dict1['email']=['koushiky@gmail.com','sai@gmail.com','mani@gmail.com']
dict1

{'Names': ['koushik', 'sai', 'mani'],
 'age': [23, 24, 25],
 'city': ['ap', 'hyderabad', 'bangalore'],
 'email': ['koushiky@gmail.com', 'sai@gmail.com', 'mani@gmail.com']}

In [81]:
# Final Dictionary
dict1

{'Names': ['koushik', 'sai', 'mani'],
 'age': [23, 24, 25],
 'city': ['ap', 'hyderabad', 'bangalore'],
 'email': ['koushiky@gmail.com', 'sai@gmail.com', 'mani@gmail.com']}

In [ ]:
#Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [88]:
def vote_eligibility(age):
    if age>=18:
        print("you can vote")
    else:
        print("you cannot vote since your age is : " ,age)
age=int(input("enter your age :"))
vote_eligibility(age)

enter your age : 16


you cannot vote since your age is :  16


In [93]:
''' 6 .Given a 'marks' variable, print the grade:
90 and above: 'A'
75–89: 'B'
50–74: 'C'
Below 50: 'Fail'''

" 6 .Given a 'marks' variable, print the grade:\n90 and above: 'A'\n75–89: 'B'\n50–74: 'C'\nBelow 50: 'Fail"

In [94]:
def grade(marks):
    if marks>=90:
        print(" your grade is A")
    elif marks>=75 and marks<=89:
        print("Your grade is B")
    elif marks>=50 and marks<=74:
        print("Your grade is C")
    else:
        print("You are Fail")
marks=int(input("Enter your marks: "))
grade(marks)
    

Enter your marks:  90


 your grade is A


In [ ]:
# 7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [96]:
def number(n):
    if n>0:
        if n%2==0:
            print(' it is positive and even number .')
        else:
            print(' it is positive and odd number.')
    elif n==0:
        print('it is zero.')
    else:
        print('it is a negitive number.')
n=int(input('enter a number :'))
number(n)
        

enter a number : 4


 it is positive and even number .


In [98]:
#section b : numpy 


In [99]:
''' 8.Create:
A scalar using np.array(5)
A 1D array with values 1 to 5
A 2D array (2x3) with values from 10 to 60 in steps of 10'''

' 8.Create:\nA scalar using np.array(5)\nA 1D array with values 1 to 5\nA 2D array (2x3) with values from 10 to 60 in steps of 10'

In [101]:
#A scalar using np.array(5)
import numpy as np
scalar = np.array(5)
print("Scalar:")
print(scalar)

Scalar:
5


In [102]:
# A 1D array with values 1 to 5
one_dim=np.array([1,2,3,4,5])
one_dim

array([1, 2, 3, 4, 5])

In [103]:
# A 2D array (2x3) with values from 10 to 60 in steps of 10
two_dim=np.array([[10, 20, 30], [40, 50, 60]])
two_dim

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
#9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [107]:
k=np.random.randint(0,100,16).reshape(4,4)
k

array([[16, 89, 60, 57],
       [34, 54, 77,  0],
       [55, 19, 27, 27],
       [10, 86, 82, 79]], dtype=int32)

In [ ]:
#10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [108]:
two_dim= np.array([[1,3,6],[9,11,15],[18,20,21]])
two_dim

array([[ 1,  3,  6],
       [ 9, 11, 15],
       [18, 20, 21]])

In [109]:
# Converting 2D into a Pandas DataFrame and adding column names:'A','B','C'.

In [111]:
import pandas as pd
df=pd.DataFrame(two_dim,columns=['A','B','C'])
df

A   B   C
0   1   3   6
1   9  11  15
2  18  20  21

In [113]:
#Section C: Exploring Panda

In [114]:
''' 11 .Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
Use .info(), .describe()
Select 'Name' and 'City' columns
Drop 'City' column
Fill any missing values in 'Salary' column with the mean
Remove any duplicate rows'''

" 11 .Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:\nUse .info(), .describe()\nSelect 'Name' and 'City' columns\nDrop 'City' column\nFill any missing values in 'Salary' column with the mean\nRemove any duplicate rows"

In [115]:
# Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'.
df= {'Name': ['koushik', 'sai', 'mani', 'deva', 'parthiban', 'kabir', 'Babu', 'rajini', 'surya', 'nani'],
    'Age': [28, 24, 35, 32, 24, 24, 40, 29, 33, 30],
    'City': ['tirupathi', 'mumbai', 'delhi', 'vellore', 'kashmir', 'Pune', 'vijayawada', 'kerala', 'chennai', 'ongole'],
    'Salary': [70000, 80000, 55000, 75000, 64000, 60000, 72000, 62000, 68000, 59000]}

In [118]:
df=pd.DataFrame(df)
df

Name  Age        City  Salary
0    koushik   28   tirupathi   70000
1        sai   24      mumbai   80000
2       mani   35       delhi   55000
3       deva   32     vellore   75000
4  parthiban   24     kashmir   64000
5      kabir   24        Pune   60000
6       Babu   40  vijayawada   72000
7     rajini   29      kerala   62000
8      surya   33     chennai   68000
9       nani   30      ongole   59000

In [119]:
# using .info(), .describe()


In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [121]:
df.describe()

Age        Salary
count  10.000000     10.000000
mean   29.900000  66500.000000
std     5.279941   7863.417408
min    24.000000  55000.000000
25%    25.000000  60500.000000
50%    29.500000  66000.000000
75%    32.750000  71500.000000
max    40.000000  80000.000000

In [124]:
# select 'name' and 'city' columns
df[['Name','City']]

Name        City
0    koushik   tirupathi
1        sai      mumbai
2       mani       delhi
3       deva     vellore
4  parthiban     kashmir
5      kabir        Pune
6       Babu  vijayawada
7     rajini      kerala
8      surya     chennai
9       nani      ongole

In [126]:
# drop 'city' column
df.drop('City',axis=1)

Name  Age  Salary
0    koushik   28   70000
1        sai   24   80000
2       mani   35   55000
3       deva   32   75000
4  parthiban   24   64000
5      kabir   24   60000
6       Babu   40   72000
7     rajini   29   62000
8      surya   33   68000
9       nani   30   59000

In [128]:
# Filling any missing values in 'Salary' column with the mean
mean_of_salary=df['Salary'].mean()
df['Salary']=df['Salary'].fillna(mean_of_salary)
print(df)

        Name  Age        City  Salary
0    koushik   28   tirupathi   70000
1        sai   24      mumbai   80000
2       mani   35       delhi   55000
3       deva   32     vellore   75000
4  parthiban   24     kashmir   64000
5      kabir   24        Pune   60000
6       Babu   40  vijayawada   72000
7     rajini   29      kerala   62000
8      surya   33     chennai   68000
9       nani   30      ongole   59000


In [131]:
# Remove any duplicate rows
df.drop_duplicates()

Name  Age        City  Salary
0    koushik   28   tirupathi   70000
1        sai   24      mumbai   80000
2       mani   35       delhi   55000
3       deva   32     vellore   75000
4  parthiban   24     kashmir   64000
5      kabir   24        Pune   60000
6       Babu   40  vijayawada   72000
7     rajini   29      kerala   62000
8      surya   33     chennai   68000
9       nani   30      ongole   59000